apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: inference-budget-controller
    app.kubernetes.io/part-of: inference-budget-controller
    app.kubernetes.io/managed-by: kustomize
  name: inference-budget-controller
  namespace: inference
